### ISSUE TITLE
Add 4 dummys

### ISSUE THREAD

**Issue by itubetw** [chillerbot/chillerbot-ux#109]
With adding this function this client will getting more users. I see everywhere who people write: 4 dummy client etc. It would be the best feature for me if I play on blmapchill. So I don't need to tab out and in! So. What do you wait. Start coding now uwu

**Comment by ChillerDragon** [comment]
Huh why close? I mean it would be cool for sure. For me personally running two clients works perfectly already. But I know some windows users struggle with instant tabbing between clients. It just requires a bit much effort and maintenance do implement and keep it in the client while updating to newer ddnet versions.

**Comment by ChillerDragon** [comment]
Duplicate of https://github.com/chillerbot/chillerbot-ux/issues/160
