### ISSUE TITLE
Client crashes when trying to load a map

### ISSUE THREAD

**Issue by SoulyVEVO** [chillerbot/chillerbot-ux#131]

**Comment by ChillerDragon** [comment]
I can not reproduce.

Which map? What does load mean? Connect to a server? Open in editor? Do you have a crash log? Does it happen every time, if not can you somehow reproduce? On windows? Does it break in ddnet too?

The crashlogs should be in ``%APPDATA%\.teeworlds\dumps`` or wherever it is on your system.

I will try merging with ddnet again lets see :shrug:

**Comment by SoulyVEVO** [comment]
same thing happens when trying to append another map so maybe its some issue with loading all the maps data?

**Comment by SoulyVEVO** [comment]
and ye i tried updating the client and it still crashes

**Comment by ChillerDragon** [comment]
soli claimed on discord it fixed
