### ISSUE TITLE
editor :s

### ISSUE THREAD

**Issue by Arylz** [chillerbot/chillerbot-ux#153]
![image](https://github.com/chillerbot/chillerbot-ux/assets/157623379/2db60704-8b58-4868-8388-cbeb8a1d4b7f)

**Comment by Arylz** [comment]
this happened when i wanted to use f-ddrace gametiles

**Comment by Arylz** [comment]
u need update GPU driver to latest version

**Comment by ChillerDragon** [comment]
Thanks for reporting the solution :heart:
