### ISSUE TITLE
add warlist mode selector.

### ISSUE THREAD

**Issue by 3x1sT** [chillerbot/chillerbot-ux#159]
i have more than 330 wars, 6 teams, 287 neutrals, and 30 traitors. and now in last update im lost my warlist.
about idea: and a comand or buttom and if it enabled then old warlist using if not then simple.
Or make script to transfer old warlist to new.

**Comment by ChillerDragon** [comment]
Do ``cl_war_list_advanced 1`` to get your old warlist back :)

**Comment by 3x1sT** [comment]
> Do `cl_war_list_advanced 1` to get your old warlist back :)

huh, thx
