### ISSUE TITLE
Auto tag reply feature

### ISSUE THREAD

**Issue by SoulyVEVO** [chillerbot/chillerbot-ux#16]
Add config for auto tag reply feature, basically each time someone tags you, you reply with the specific message that you set ealier.

Example when message is set to "no u": 
**nameless tee:** hi Souly
**Souly:** no u

**Comment by ChillerDragon** [comment]
@SoulyVEVO 

```
cl_auto_reply_msg "no u"
cl_auto_reply 1
```

btw you can also ping back using
```
cl_auto_reply_msg "no u %n"
cl_auto_reply 1
```
