### ISSUE TITLE
Auto reply bugs

### ISSUE THREAD

**Issue by SoulyVEVO** [chillerbot/chillerbot-ux#19]
- Auto reply doesnt ignore muted users
- Besides normal chat it also replies to Server messages (including whisper)
- It doesnt reply to "duplicate" messages with [1] prefix

**Comment by ChillerDragon** [comment]
>     * Auto reply doesnt ignore muted users

I do not understand what that means.

>     * Besides normal chat it also replies to Server messages (including whisper)

Some server messages are sent directly to the client and I agree responding to those can be seen as bug. But responding to things like /me in ddnet can be seen as a feature. Not sure.

>     * It doesnt reply to "duplicate" messages with [1] prefix

Intended behavior to avoid useless spam or loops with fellow chillerbots

**Comment by SoulyVEVO** [comment]
> > ```
> > * Auto reply doesnt ignore muted users
> > ```
> 
> I do not understand what that means.
> 

@ChillerDragon by muted players i meant foes (add_foe command), they can type something in chat and even tho you cant see their message in chat itself, you are still replying to it.

> > ```
> > * Besides normal chat it also replies to Server messages (including whisper)
> > ```
> 
> Some server messages are sent directly to the client and I agree responding to those can be seen as bug. But responding to things like /me in ddnet can be seen as a feature. Not sure.
> 
Maybe you could do some detection for that **###** prefix, then we wont have to worry about it activating upon f.e. finishing a map but it will activate upon getting a /me message.

> > ```
> > * It doesnt reply to "duplicate" messages with [1] prefix
> > ```
> 
> Intended behavior to avoid useless spam or loops with fellow chillerbots

For the duplicate messages maybe add a delay instead of completly ignoring the message, sometimes.

I also noticed that auto reply acts a little weird since spam protection was added, basically whenever someone tags me, his next message that includes tag needs to be different for auto reply to work, even if player said something different in the way.

For example:
```
player: Souly:
Souly: "reply"
player: a
player: b
player: Souly:
"no reply"
```
Not sure if its a bug or not but i found it weird.
For it to reply again, the same player would need to include something in the message like "Souly: a"
Its still pretty easy to bypass the spam protection by typing 2 different messages alternately.

**Comment by ChillerDragon** [comment]
Replying to whisper is intended behavior. My main use case for that feature is inform players when my chat is turned off so whisper makes sense too. The spam filter is easy to bypass yet effective in most cases. If players already got a response there is no need to inform them again. This feature is not optimized for spamming.
