### ISSUE TITLE
Editor: click tile to select layer

### ISSUE THREAD

**Issue by ChillerDragon** [chillerbot/chillerbot-ux#23]
Sometimes it is hard to find the layer for the tile one is currently trying to edit especially when picking up old big maps with tons of doodads. Would be nice if ctrl+click or something similar could iterate over a selection of all layers having tiles currently under the cursor.

**Comment by SoulyVEVO** [comment]
yes pls

**Comment by ChillerDragon** [comment]
Merged into upstream
