### ISSUE TITLE
Can't get autologin to work

### ISSUE THREAD

**Issue by o-be-one** [chillerbot/chillerbot-ux#31]
Hello,

**OS:** Debian latest (as Docker container)
**Version:** chillberbot-ux latest headless from Github (script "strip_gfx.py" cleaned all gfx parts)
**Usecase:** used as an headless bot under Linux on fokkonaut playground

Well so my chillerbot-ux is not able to auto login and i don't see any error message so probably it's not even trying.

The compiled bin location is `/chillerbot-ux`. I've tried to put the chillpw_secret.txt in the following paths:
- `~/.teeworlds//chillerbot/chillpw_secret.txt`
- `/chillerbot/chillpw_secret.txt`
- `/chillpw_secret.txt`

Content of the file:
```
51.210.171.47:7303,0,say /login LOGIN1 PASSWORD1
51.210.171.47:7303,1,say /login LOGIN2 PASSWORD2
```

Let me know if there is missing informations, hope you'll be able to help ^^.

Thanks

**Comment by SoulyVEVO** [comment]
does it not work only on fokkonauts server or on all servers?
I think it was executed only after map loading which seems to be somewhat broken on that server.

**Comment by o-be-one** [comment]
I only use it on fokko server; so yeah related to this one on my side.

**Comment by ChillerDragon** [comment]
It was an issue with the strip_gfx.py script. The client did not render any components. And the password manager authenticates in OnRender() to have some delay between login attempts and do not spam all in first tick. I fixed the script in https://github.com/chillerbot/chillerbot-ux/commit/f71c8d30aebf0e4b47885ae2494c2105cd08ad2d which now fakes a working graphics backend and thus all components get rendered.

Also tested with docker using

```dockerfile
FROM debian:11

RUN apt-get update && apt-get install \
	build-essential \
	cmake \
	git \
	libcurl4-openssl-dev \
	libssl-dev \
	libfreetype6-dev \
	libglew-dev \
	libnotify-dev \
	libogg-dev \
	libopus-dev \
	libopusfile-dev \
	libpnglite-dev \
	libsdl2-dev \
	libsqlite3-dev \
	libwavpack-dev \
	python \
	google-mock -y

RUN git clone --recursive https://github.com/chillerbot/chillerbot-ux /chillerbot-ux

RUN cd /chillerbot-ux && ./scripts/strip_gfx.py -i
RUN cd /chillerbot-ux && mkdir build && cd build && cmake .. && make

RUN mkdir -p /root/.teeworlds/chillerbot/
RUN printf '%s\n' '51.210.171.47:7303,0,say hi from docker' > /root/.teeworlds/chillerbot/chillpw_secret.txt
RUN printf '%s\n' '51.210.171.47:7303,1,say hi from docker dummy' >> /root/.teeworlds/chillerbot/chillpw_secret.txt
RUN printf '%s\n' '51.210.171.47:7303,0,say /login dockerux test' >> /root/.teeworlds/chillerbot/chillpw_secret.txt

WORKDIR /chillerbot-ux/build
CMD ["./chillerbot-ux", "connect 51.210.171.47:7303"]
```
