### ISSUE TITLE
big chungus quote in loading

### ISSUE THREAD

**Issue by sss75m4** [chillerbot/chillerbot-ux#44]
"big chungus is funny" add this chungus quote to chillerbot it will be good i Think. suggestions appreciated and feedback also. appreciated.

**Comment by ChillerDragon** [comment]
You mean extend those here?

https://github.com/chillerbot/chillerbot-ux/blob/1a661ae93d5280af485bfd78ed21499ece2ca492/src/game/client/components/menus.cpp#L961-L968

**Comment by sss75m4** [comment]
yes close the mfing issue
