### ISSUE TITLE
Glow skins support

### ISSUE THREAD

**Issue by SoulyVEVO** [chillerbot/chillerbot-ux#53]
the idea is to give player a glow skin effect around, brighten the skin up and add `glow_` prefix to its name without needing additional skin file while also showing it on other player when using the same skin name prefix

not sure if u can do it tho

**Comment by ChillerDragon** [comment]
> not sure if u can do it tho

Everything is possible.

But I ain't no render guru. So this will be too much effort for me. Also such heavy code change will make updating to latest ddnet version harder.
