### ISSUE TITLE
Add spike tile tracer

### ISSUE THREAD

**Issue by ChillerDragon** [chillerbot/chillerbot-ux#55]
Draw lines to closest spike tiles maybe colorize depending on distance.

Would help a lot in playing Back In Time maps -,-

**Comment by ChillerDragon** [comment]
But only if nothing intersects. False postivives behind wall is annoying

**Comment by SoulyVEVO** [comment]
chot

**Comment by ChillerDragon** [comment]
![screenshot_2022-03-31_13-42-08](https://user-images.githubusercontent.com/20344300/161047399-62a8f30b-ff69-4c5e-977c-5bd851e3d2bf.png)
![screenshot_2022-03-31_13-42-32](https://user-images.githubusercontent.com/20344300/161047415-a35dd1be-e9a6-4c7f-bbd1-ab085085f74d.png)

The code is crap. But idc even my laptop runs smooth on max distance.
